version: "3"

services:
  web-dev:
    build: .
    image: docker-web-dev
    ports:
      # "local port:web server port running in docker container"
      - "3000:3000"
      - "8080:8080"
    volumes:
      # "local work directory:docker work directory"
      - "/Users/younwang/Documents/workspace:/workspace"
    stdin_open: true
    tty: true
